// Converts the BDF files in /fonts into a compact TypeScript module that both
// the browser editor and the server renderer import.
//
// Glyph encoding: "dwidth,w,h,xoff,yoff,rows" where rows is the BDF hex bitmap
// rows concatenated (each row is ceil(w/8)*2 hex digits).
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const FONTS: { id: string; file: string; label: string }[] = [
  { id: "tom-thumb", file: "tom-thumb.bdf", label: "Tom Thumb (4×6)" },
  { id: "CG-pixel-3x5", file: "CG-pixel-3x5-mono.bdf", label: "CG Pixel 3×5" },
  { id: "CG-pixel-4x5", file: "CG-pixel-4x5-mono.bdf", label: "CG Pixel 4×5" },
  { id: "tb-8", file: "tb-8.bdf", label: "TB-8 (Tidbyt default)" },
  { id: "5x8", file: "5x8.bdf", label: "5×8" },
  { id: "6x10", file: "6x10.bdf", label: "6×10" },
  { id: "Dina", file: "Dina_r400-6.bdf", label: "Dina 6" },
  { id: "6x13", file: "6x13.bdf", label: "6×13" },
  { id: "7x13B", file: "7x13B.bdf", label: "7×13 Bold" },
  { id: "9x15B", file: "9x15B.bdf", label: "9×15 Bold" },
  { id: "spleen-16", file: "spleen-8x16.bdf", label: "Spleen 16" },
  { id: "terminus-16b", file: "ter-u16b.bdf", label: "Terminus Bold 16" },
  { id: "9x18B", file: "9x18B.bdf", label: "9×18 Bold" },
  { id: "10x20", file: "10x20.bdf", label: "10×20" },
  { id: "terminus-20b", file: "ter-u20b.bdf", label: "Terminus Bold 20" },
  { id: "spleen-24", file: "spleen-12x24.bdf", label: "Spleen 24" },
  { id: "terminus-24b", file: "ter-u24b.bdf", label: "Terminus Bold 24" },
  { id: "terminus-28b", file: "ter-u28b.bdf", label: "Terminus Bold 28" },
  { id: "spleen-32", file: "spleen-16x32.bdf", label: "Spleen 32" },
  { id: "terminus-32b", file: "ter-u32b.bdf", label: "Terminus Bold 32" },
];

// Latin-1, Cyrillic (Russian, Ukrainian and more), plus a handful of
// typographic/arrow glyphs useful on a ticker.
const EXTRA = [0x2013, 0x2014, 0x2018, 0x2019, 0x201c, 0x201d, 0x2022, 0x2026, 0x20ac, 0x2190, 0x2191, 0x2192, 0x2193];
const wanted = (cp: number) => (cp >= 32 && cp <= 126) || (cp >= 160 && cp <= 255) || (cp >= 0x0400 && cp <= 0x04ff) || EXTRA.includes(cp);

function parse(src: string) {
  const lines = src.split(/\r?\n/);
  let ascent = 0;
  let descent = 0;
  const glyphs: Record<number, string> = {};
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.startsWith("FONT_ASCENT ")) ascent = Number(line.split(" ")[1]);
    else if (line.startsWith("FONT_DESCENT ")) descent = Number(line.split(" ")[1]);
    else if (line.startsWith("STARTCHAR")) {
      let enc = -1;
      let dw = 0;
      let bbx = [0, 0, 0, 0];
      const rows: string[] = [];
      for (i++; i < lines.length && !lines[i].startsWith("ENDCHAR"); i++) {
        const l = lines[i];
        if (l.startsWith("ENCODING ")) enc = Number(l.split(/\s+/)[1]);
        else if (l.startsWith("DWIDTH ")) dw = Number(l.split(/\s+/)[1]);
        else if (l.startsWith("BBX ")) bbx = l.split(/\s+/).slice(1, 5).map(Number);
        else if (l.startsWith("BITMAP")) {
          for (i++; i < lines.length && !lines[i].startsWith("ENDCHAR"); i++) rows.push(lines[i].trim());
          i--;
        }
      }
      if (!wanted(enc)) continue;
      const nib = Math.ceil(bbx[0] / 8) * 2;
      const hex = rows.map((r) => r.padEnd(nib, "0").slice(0, nib)).join("");
      glyphs[enc] = [dw, ...bbx, hex].join(",");
    }
  }
  return { ascent, descent, glyphs };
}

const out: Record<string, unknown> = {};
for (const f of FONTS) {
  const parsed = parse(readFileSync(join("fonts", f.file), "utf8"));
  out[f.id] = { label: f.label, ...parsed };
  console.log(`${f.id}: ${Object.keys(parsed.glyphs).length} glyphs, ascent ${parsed.ascent}, descent ${parsed.descent}`);
}

writeFileSync(
  join("src", "shared", "fontdata.ts"),
  "// Generated by scripts/build-fonts.ts — do not edit.\n" +
    "export const FONT_DATA: Record<string, { label: string; ascent: number; descent: number; glyphs: Record<number, string> }> = " +
    JSON.stringify(out) +
    ";\n",
);
